import { DecisionAnalysis } from "../types";

export function formatDecisionToMarkdown(analysis: DecisionAnalysis): string {
  const verdict = analysis.tiebreakerVerdict;
  let md = `# THE TIEBREAKER — DECISION BRIEFING\n\n`;
  md += `**Dilemma**: ${analysis.question}\n`;
  md += `**Evaluated On**: ${new Date(analysis.createdAt).toLocaleDateString()}\n\n`;
  md += `## Executive Summary\n${analysis.summary}\n\n`;

  md += `## ⚖️ The Tiebreaker Verdict\n`;
  md += `**Recommended Choice**: ${verdict.recommendedOptionTitle} (${verdict.confidencePercentage}% Confidence)\n\n`;
  md += `**The Core Trade-off**: "${verdict.coreDilemma}"\n\n`;
  md += `**Primary Rationale**: ${verdict.primaryReason}\n\n`;
  md += `**Regret Minimization (10-Year Test)**: ${verdict.regretMinimizationVerdict}\n\n`;

  md += `### If-Then Heuristics:\n`;
  verdict.ifThenRules.forEach((rule, idx) => {
    md += `- **Rule ${idx + 1}**: If ${rule.condition} → Choose **${rule.recommendation}** (${rule.rationale})\n`;
  });
  md += `\n`;

  md += `### Immediate 3-Step Momentum Plan:\n`;
  verdict.immediateNextSteps.forEach((step, idx) => {
    md += `${idx + 1}. ${step}\n`;
  });
  md += `\n`;

  md += `## 📊 Options Evaluated\n\n`;
  analysis.options.forEach((opt) => {
    md += `### ${opt.title}\n*${opt.tagline}*\n\n`;
    md += `**Pros:**\n`;
    opt.pros
      .filter((p) => !p.userExcluded)
      .forEach((p) => {
        md += `+ [Impact: ${p.impact.toUpperCase()}, Weight: +${p.weight}] **${p.point}**: ${p.detail}\n`;
      });
    md += `\n**Cons:**\n`;
    opt.cons
      .filter((c) => !c.userExcluded)
      .forEach((c) => {
        md += `- [Impact: ${c.impact.toUpperCase()}, Weight: -${c.weight}] **${c.point}**: ${c.detail}\n`;
      });
    md += `\n**SWOT Summary:**\n`;
    md += `- **Strengths**: ${opt.swot.strengths.join("; ")}\n`;
    md += `- **Weaknesses**: ${opt.swot.weaknesses.join("; ")}\n`;
    md += `- **Opportunities**: ${opt.swot.opportunities.join("; ")}\n`;
    md += `- **Threats**: ${opt.swot.threats.join("; ")}\n`;
    md += `- **Mitigation Strategy**: ${opt.swot.mitigationAdvice}\n\n`;
  });

  md += `## 📈 Multi-Criteria Comparison Matrix\n\n`;
  analysis.comparisonMatrix.criteria.forEach((crit) => {
    md += `### ${crit.name} (${crit.importance.toUpperCase()} priority)\n${crit.description}\n`;
    crit.scores.forEach((s) => {
      const opt = analysis.options.find((o) => o.id === s.optionId);
      md += `- **${opt?.title || s.optionId}**: ${s.score}/10 — ${s.note}\n`;
    });
    md += `\n`;
  });

  md += `---\n*Generated by The Tiebreaker AI Deliberation Engine*`;
  return md;
}
